# Generated by Django 5.0 on 2024-01-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcondition',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
