# Generated by Django 5.0.1 on 2024-01-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_remove_appointment_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('success', 'Success')], default='failed', max_length=10),
        ),
    ]
